<?xml version="1.0" encoding="utf-8"?><Database Name="BD_GERD_SLA_DES" Class="ConfigurationDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=172.25.81.78;Initial Catalog=SGR_Desav3;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SGR_Desav3ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TB_MAE_Configuracion" Member="Configs">
    <Type Name="Config">
      <Column Name="CONF_Nombre" Member="name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="CONF_Descripcion" Member="description" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="CONF_Valor" Member="value" Type="System.String" DbType="VarChar(8000) NOT NULL" CanBeNull="false" />
      <Column Name="CONF_Token" Member="token" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>