#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Endpoints.Payment.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BD_Base")]
	public partial class paymentDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertDATAPAYMENT(DATAPAYMENT instance);
    partial void UpdateDATAPAYMENT(DATAPAYMENT instance);
    partial void DeleteDATAPAYMENT(DATAPAYMENT instance);
    #endregion
		
		public paymentDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BD_BaseConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public paymentDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public paymentDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public paymentDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public paymentDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CREATEPAYMENT> CREATEPAYMENT
		{
			get
			{
				return this.GetTable<CREATEPAYMENT>();
			}
		}
		
		public System.Data.Linq.Table<DATAPAYMENT> DATAPAYMENT
		{
			get
			{
				return this.GetTable<DATAPAYMENT>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class CREATEPAYMENT
	{
		
		private System.Guid _TOKENCASE;
		
		private string _VOUCHER;
		
		private int _VALUE;
		
		public CREATEPAYMENT()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="TOKEN", Storage="_TOKENCASE")]
		public System.Guid TOKENCASE
		{
			get
			{
				return this._TOKENCASE;
			}
			set
			{
				if ((this._TOKENCASE != value))
				{
					this._TOKENCASE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="COMPROBANTE", Storage="_VOUCHER", CanBeNull=false)]
		public string VOUCHER
		{
			get
			{
				return this._VOUCHER;
			}
			set
			{
				if ((this._VOUCHER != value))
				{
					this._VOUCHER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="MONTOPAGO", Storage="_VALUE")]
		public int VALUE
		{
			get
			{
				return this._VALUE;
			}
			set
			{
				if ((this._VALUE != value))
				{
					this._VALUE = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_PAGO")]
	public partial class DATAPAYMENT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CODE;
		
		private string _VOUCHER;
		
		private System.Nullable<int> _VALUE;
		
		private System.Nullable<System.DateTime> _DATE;
		
		private System.Nullable<int> _CASECODE;
		
		private System.Nullable<System.Guid> _TOKEN;
		
		private System.Nullable<System.Guid> _CASETOKEN;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODEChanging(int value);
    partial void OnCODEChanged();
    partial void OnVOUCHERChanging(string value);
    partial void OnVOUCHERChanged();
    partial void OnVALUEChanging(System.Nullable<int> value);
    partial void OnVALUEChanged();
    partial void OnDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnDATEChanged();
    partial void OnCASECODEChanging(System.Nullable<int> value);
    partial void OnCASECODEChanged();
    partial void OnTOKENChanging(System.Nullable<System.Guid> value);
    partial void OnTOKENChanged();
    partial void OnCASETOKENChanging(System.Nullable<System.Guid> value);
    partial void OnCASETOKENChanged();
    #endregion
		
		public DATAPAYMENT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="PAGO_CODIGO", Storage="_CODE", DbType="Int NOT NULL")]
		public int CODE
		{
			get
			{
				return this._CODE;
			}
			set
			{
				if ((this._CODE != value))
				{
					this.OnCODEChanging(value);
					this.SendPropertyChanging();
					this._CODE = value;
					this.SendPropertyChanged("CODE");
					this.OnCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="PAGO_COMPROBANTE", Storage="_VOUCHER", DbType="VarChar(50)")]
		public string VOUCHER
		{
			get
			{
				return this._VOUCHER;
			}
			set
			{
				if ((this._VOUCHER != value))
				{
					this.OnVOUCHERChanging(value);
					this.SendPropertyChanging();
					this._VOUCHER = value;
					this.SendPropertyChanged("VOUCHER");
					this.OnVOUCHERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="PAGO_MONTO", Storage="_VALUE", DbType="Int")]
		public System.Nullable<int> VALUE
		{
			get
			{
				return this._VALUE;
			}
			set
			{
				if ((this._VALUE != value))
				{
					this.OnVALUEChanging(value);
					this.SendPropertyChanging();
					this._VALUE = value;
					this.SendPropertyChanged("VALUE");
					this.OnVALUEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="PAGO_FECHA", Storage="_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATE
		{
			get
			{
				return this._DATE;
			}
			set
			{
				if ((this._DATE != value))
				{
					this.OnDATEChanging(value);
					this.SendPropertyChanging();
					this._DATE = value;
					this.SendPropertyChanged("DATE");
					this.OnDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="PAGO_CASO_CODIGO", Storage="_CASECODE", DbType="Int")]
		public System.Nullable<int> CASECODE
		{
			get
			{
				return this._CASECODE;
			}
			set
			{
				if ((this._CASECODE != value))
				{
					this.OnCASECODEChanging(value);
					this.SendPropertyChanging();
					this._CASECODE = value;
					this.SendPropertyChanged("CASECODE");
					this.OnCASECODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="PAGO_TOKEN", Storage="_TOKEN", DbType="UniqueIdentifier", IsPrimaryKey=true)]
		public System.Nullable<System.Guid> TOKEN
		{
			get
			{
				return this._TOKEN;
			}
			set
			{
				if ((this._TOKEN != value))
				{
					this.OnTOKENChanging(value);
					this.SendPropertyChanging();
					this._TOKEN = value;
					this.SendPropertyChanged("TOKEN");
					this.OnTOKENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="CASO_TOKEN", Storage="_CASETOKEN", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> CASETOKEN
		{
			get
			{
				return this._CASETOKEN;
			}
			set
			{
				if ((this._CASETOKEN != value))
				{
					this.OnCASETOKENChanging(value);
					this.SendPropertyChanging();
					this._CASETOKEN = value;
					this.SendPropertyChanged("CASETOKEN");
					this.OnCASETOKENChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
