#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Endpoints.Manager.Client.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BD_Base")]
	public partial class clientDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertDATACLIENT(DATACLIENT instance);
    partial void UpdateDATACLIENT(DATACLIENT instance);
    partial void DeleteDATACLIENT(DATACLIENT instance);
    #endregion
		
		public clientDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BD_BaseConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public clientDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public clientDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public clientDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public clientDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CREATECLIENT> CREATECLIENT
		{
			get
			{
				return this.GetTable<CREATECLIENT>();
			}
		}
		
		public System.Data.Linq.Table<DATACLIENT> DATACLIENT
		{
			get
			{
				return this.GetTable<DATACLIENT>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class CREATECLIENT
	{
		
		private string _NAME;
		
		private string _LASTNAME;
		
		private string _EMAIL;
		
		private int _MOBILE;
		
		private int _PHONE;
		
		private int _RUT;
		
		private string _DV;
		
		private System.Guid _TOKEN;
		
		public CREATECLIENT()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", CanBeNull=false)]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LASTNAME", CanBeNull=false)]
		public string LASTNAME
		{
			get
			{
				return this._LASTNAME;
			}
			set
			{
				if ((this._LASTNAME != value))
				{
					this._LASTNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", CanBeNull=false)]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this._EMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOBILE")]
		public int MOBILE
		{
			get
			{
				return this._MOBILE;
			}
			set
			{
				if ((this._MOBILE != value))
				{
					this._MOBILE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHONE")]
		public int PHONE
		{
			get
			{
				return this._PHONE;
			}
			set
			{
				if ((this._PHONE != value))
				{
					this._PHONE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RUT")]
		public int RUT
		{
			get
			{
				return this._RUT;
			}
			set
			{
				if ((this._RUT != value))
				{
					this._RUT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DV", CanBeNull=false)]
		public string DV
		{
			get
			{
				return this._DV;
			}
			set
			{
				if ((this._DV != value))
				{
					this._DV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOKEN")]
		public System.Guid TOKEN
		{
			get
			{
				return this._TOKEN;
			}
			set
			{
				if ((this._TOKEN != value))
				{
					this._TOKEN = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_CLIENTE")]
	public partial class DATACLIENT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _NAME;
		
		private string _LASTNAME;
		
		private string _EMAIL;
		
		private System.Nullable<int> _MOBILE;
		
		private System.Nullable<int> _PHONE;
		
		private System.Guid _TOKEN;
		
		private int _RUT;
		
		private string _DV;
		
		private int _CANTIDAD;
		
		private int _TOTAL;
		
		private int _DEUDA;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    partial void OnLASTNAMEChanging(string value);
    partial void OnLASTNAMEChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnMOBILEChanging(System.Nullable<int> value);
    partial void OnMOBILEChanged();
    partial void OnPHONEChanging(System.Nullable<int> value);
    partial void OnPHONEChanged();
    partial void OnTOKENChanging(System.Guid value);
    partial void OnTOKENChanged();
    partial void OnRUTChanging(int value);
    partial void OnRUTChanged();
    partial void OnDVChanging(string value);
    partial void OnDVChanged();
    partial void OnCANTIDADChanging(int value);
    partial void OnCANTIDADChanged();
    partial void OnTOTALChanging(int value);
    partial void OnTOTALChanged();
    partial void OnDEUDAChanging(int value);
    partial void OnDEUDAChanged();
    #endregion
		
		public DATACLIENT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="CLIE_NOMBRE", Storage="_NAME", DbType="VarChar(50)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="CLIE_APELLIDOS", Storage="_LASTNAME", DbType="VarChar(50)")]
		public string LASTNAME
		{
			get
			{
				return this._LASTNAME;
			}
			set
			{
				if ((this._LASTNAME != value))
				{
					this.OnLASTNAMEChanging(value);
					this.SendPropertyChanging();
					this._LASTNAME = value;
					this.SendPropertyChanged("LASTNAME");
					this.OnLASTNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="CLIE_EMAIL", Storage="_EMAIL", DbType="VarChar(50)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="CLIE_CELULAR", Storage="_MOBILE", DbType="Int")]
		public System.Nullable<int> MOBILE
		{
			get
			{
				return this._MOBILE;
			}
			set
			{
				if ((this._MOBILE != value))
				{
					this.OnMOBILEChanging(value);
					this.SendPropertyChanging();
					this._MOBILE = value;
					this.SendPropertyChanged("MOBILE");
					this.OnMOBILEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="CLIE_TELEFONO", Storage="_PHONE", DbType="Int")]
		public System.Nullable<int> PHONE
		{
			get
			{
				return this._PHONE;
			}
			set
			{
				if ((this._PHONE != value))
				{
					this.OnPHONEChanging(value);
					this.SendPropertyChanging();
					this._PHONE = value;
					this.SendPropertyChanged("PHONE");
					this.OnPHONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="CLIE_TOKEN", Storage="_TOKEN", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid TOKEN
		{
			get
			{
				return this._TOKEN;
			}
			set
			{
				if ((this._TOKEN != value))
				{
					this.OnTOKENChanging(value);
					this.SendPropertyChanging();
					this._TOKEN = value;
					this.SendPropertyChanged("TOKEN");
					this.OnTOKENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="CLIE_RUT", Storage="_RUT")]
		public int RUT
		{
			get
			{
				return this._RUT;
			}
			set
			{
				if ((this._RUT != value))
				{
					this.OnRUTChanging(value);
					this.SendPropertyChanging();
					this._RUT = value;
					this.SendPropertyChanged("RUT");
					this.OnRUTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="CLIE_DV", Storage="_DV", CanBeNull=false)]
		public string DV
		{
			get
			{
				return this._DV;
			}
			set
			{
				if ((this._DV != value))
				{
					this.OnDVChanging(value);
					this.SendPropertyChanging();
					this._DV = value;
					this.SendPropertyChanged("DV");
					this.OnDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="CANTIDADCASOS", Storage="_CANTIDAD")]
		public int CANTIDAD
		{
			get
			{
				return this._CANTIDAD;
			}
			set
			{
				if ((this._CANTIDAD != value))
				{
					this.OnCANTIDADChanging(value);
					this.SendPropertyChanging();
					this._CANTIDAD = value;
					this.SendPropertyChanged("CANTIDAD");
					this.OnCANTIDADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="TOTALCONTRATOS", Storage="_TOTAL")]
		public int TOTAL
		{
			get
			{
				return this._TOTAL;
			}
			set
			{
				if ((this._TOTAL != value))
				{
					this.OnTOTALChanging(value);
					this.SendPropertyChanging();
					this._TOTAL = value;
					this.SendPropertyChanged("TOTAL");
					this.OnTOTALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="TOTALDEUDA", Storage="_DEUDA")]
		public int DEUDA
		{
			get
			{
				return this._DEUDA;
			}
			set
			{
				if ((this._DEUDA != value))
				{
					this.OnDEUDAChanging(value);
					this.SendPropertyChanging();
					this._DEUDA = value;
					this.SendPropertyChanged("DEUDA");
					this.OnDEUDAChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
