#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Endpoints.Account.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BD_Base")]
	public partial class authenticationDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertDATAUSER(DATAUSER instance);
    partial void UpdateDATAUSER(DATAUSER instance);
    partial void DeleteDATAUSER(DATAUSER instance);
    #endregion
		
		public authenticationDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BD_BaseConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public authenticationDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public authenticationDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public authenticationDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public authenticationDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<USER> USER
		{
			get
			{
				return this.GetTable<USER>();
			}
		}
		
		public System.Data.Linq.Table<CURRENTUSER> CURRENTUSER
		{
			get
			{
				return this.GetTable<CURRENTUSER>();
			}
		}
		
		public System.Data.Linq.Table<PASSWORDRECOVERY> PASSWORDRECOVERY
		{
			get
			{
				return this.GetTable<PASSWORDRECOVERY>();
			}
		}
		
		public System.Data.Linq.Table<DATAUSER> DATAUSER
		{
			get
			{
				return this.GetTable<DATAUSER>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class USER
	{
		
		private string _user;
		
		private string _password;
		
		public USER()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user", CanBeNull=false)]
		public string user
		{
			get
			{
				return this._user;
			}
			set
			{
				if ((this._user != value))
				{
					this._user = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_password", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this._password = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class CURRENTUSER
	{
		
		private System.Guid _nombre;
		
		private string _token;
		
		private string _nombreCompleto;
		
		private string _APELLIDO;
		
		private string _MAIL;
		
		public CURRENTUSER()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="USUA_TOKEN", Storage="_nombre")]
		public System.Guid TOKEN
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="USUA_NOMBRE_USUARIO", Storage="_token", CanBeNull=false)]
		public string NOMBREUSUARIO
		{
			get
			{
				return this._token;
			}
			set
			{
				if ((this._token != value))
				{
					this._token = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="USUA_NOMBRE", Storage="_nombreCompleto", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._nombreCompleto;
			}
			set
			{
				if ((this._nombreCompleto != value))
				{
					this._nombreCompleto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="USUA_APELLIDO", Storage="_APELLIDO", CanBeNull=false)]
		public string APELLIDO
		{
			get
			{
				return this._APELLIDO;
			}
			set
			{
				if ((this._APELLIDO != value))
				{
					this._APELLIDO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="USUA_MAIL", Storage="_MAIL", CanBeNull=false)]
		public string MAIL
		{
			get
			{
				return this._MAIL;
			}
			set
			{
				if ((this._MAIL != value))
				{
					this._MAIL = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class PASSWORDRECOVERY
	{
		
		private string _host;
		
		private string _email;
		
		public PASSWORDRECOVERY()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_host", CanBeNull=false)]
		public string host
		{
			get
			{
				return this._host;
			}
			set
			{
				if ((this._host != value))
				{
					this._host = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_USUARIO")]
	public partial class DATAUSER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _USUA_NOMBRE;
		
		private string _USUA_APELLIDO;
		
		private string _USUA_NOMBRE_USUARIO;
		
		private string _USUA_PASSWORD;
		
		private System.Nullable<bool> _USUA_ACTIVO;
		
		private System.Nullable<System.Guid> _USUA_TOKEN;
		
		private string _USUA_MAIL;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUSUA_NOMBREChanging(string value);
    partial void OnUSUA_NOMBREChanged();
    partial void OnUSUA_APELLIDOChanging(string value);
    partial void OnUSUA_APELLIDOChanged();
    partial void OnUSUA_NOMBRE_USUARIOChanging(string value);
    partial void OnUSUA_NOMBRE_USUARIOChanged();
    partial void OnUSUA_PASSWORDChanging(string value);
    partial void OnUSUA_PASSWORDChanged();
    partial void OnUSUA_ACTIVOChanging(System.Nullable<bool> value);
    partial void OnUSUA_ACTIVOChanged();
    partial void OnUSUA_TOKENChanging(System.Nullable<System.Guid> value);
    partial void OnUSUA_TOKENChanged();
    partial void OnUSUA_MAILChanging(string value);
    partial void OnUSUA_MAILChanged();
    #endregion
		
		public DATAUSER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUA_NOMBRE", DbType="VarChar(50)")]
		public string USUA_NOMBRE
		{
			get
			{
				return this._USUA_NOMBRE;
			}
			set
			{
				if ((this._USUA_NOMBRE != value))
				{
					this.OnUSUA_NOMBREChanging(value);
					this.SendPropertyChanging();
					this._USUA_NOMBRE = value;
					this.SendPropertyChanged("USUA_NOMBRE");
					this.OnUSUA_NOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUA_APELLIDO", DbType="VarChar(50)")]
		public string USUA_APELLIDO
		{
			get
			{
				return this._USUA_APELLIDO;
			}
			set
			{
				if ((this._USUA_APELLIDO != value))
				{
					this.OnUSUA_APELLIDOChanging(value);
					this.SendPropertyChanging();
					this._USUA_APELLIDO = value;
					this.SendPropertyChanged("USUA_APELLIDO");
					this.OnUSUA_APELLIDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUA_NOMBRE_USUARIO", DbType="VarChar(50)")]
		public string USUA_NOMBRE_USUARIO
		{
			get
			{
				return this._USUA_NOMBRE_USUARIO;
			}
			set
			{
				if ((this._USUA_NOMBRE_USUARIO != value))
				{
					this.OnUSUA_NOMBRE_USUARIOChanging(value);
					this.SendPropertyChanging();
					this._USUA_NOMBRE_USUARIO = value;
					this.SendPropertyChanged("USUA_NOMBRE_USUARIO");
					this.OnUSUA_NOMBRE_USUARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUA_PASSWORD", DbType="VarChar(50)")]
		public string USUA_PASSWORD
		{
			get
			{
				return this._USUA_PASSWORD;
			}
			set
			{
				if ((this._USUA_PASSWORD != value))
				{
					this.OnUSUA_PASSWORDChanging(value);
					this.SendPropertyChanging();
					this._USUA_PASSWORD = value;
					this.SendPropertyChanged("USUA_PASSWORD");
					this.OnUSUA_PASSWORDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUA_ACTIVO", DbType="Bit")]
		public System.Nullable<bool> USUA_ACTIVO
		{
			get
			{
				return this._USUA_ACTIVO;
			}
			set
			{
				if ((this._USUA_ACTIVO != value))
				{
					this.OnUSUA_ACTIVOChanging(value);
					this.SendPropertyChanging();
					this._USUA_ACTIVO = value;
					this.SendPropertyChanged("USUA_ACTIVO");
					this.OnUSUA_ACTIVOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUA_TOKEN", DbType="UniqueIdentifier", IsPrimaryKey=true)]
		public System.Nullable<System.Guid> USUA_TOKEN
		{
			get
			{
				return this._USUA_TOKEN;
			}
			set
			{
				if ((this._USUA_TOKEN != value))
				{
					this.OnUSUA_TOKENChanging(value);
					this.SendPropertyChanging();
					this._USUA_TOKEN = value;
					this.SendPropertyChanged("USUA_TOKEN");
					this.OnUSUA_TOKENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUA_MAIL", DbType="VarChar(50)")]
		public string USUA_MAIL
		{
			get
			{
				return this._USUA_MAIL;
			}
			set
			{
				if ((this._USUA_MAIL != value))
				{
					this.OnUSUA_MAILChanging(value);
					this.SendPropertyChanging();
					this._USUA_MAIL = value;
					this.SendPropertyChanged("USUA_MAIL");
					this.OnUSUA_MAILChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
