#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Endpoints.Mantenedores.Contratos.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SGR_Desav3")]
	public partial class ContratosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertCONTRATOS_LISTA(CONTRATOS_LISTA instance);
    partial void UpdateCONTRATOS_LISTA(CONTRATOS_LISTA instance);
    partial void DeleteCONTRATOS_LISTA(CONTRATOS_LISTA instance);
    #endregion
		
		public ContratosDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SGR_Desav3ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ContratosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ContratosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ContratosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ContratosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CONTRATOS_LISTA> CONTRATOS_LISTA
		{
			get
			{
				return this.GetTable<CONTRATOS_LISTA>();
			}
		}
		
		public System.Data.Linq.Table<CONTRATOS> CONTRATOS
		{
			get
			{
				return this.GetTable<CONTRATOS>();
			}
		}
		
		public System.Data.Linq.Table<CONTRATOS_NIVEL_LISTA> CONTRATOS_NIVEL_LISTA
		{
			get
			{
				return this.GetTable<CONTRATOS_NIVEL_LISTA>();
			}
		}
		
		public System.Data.Linq.Table<CONTRATOS_NIVEL> CONTRATOS_NIVEL
		{
			get
			{
				return this.GetTable<CONTRATOS_NIVEL>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VI_CONTRATOS")]
	public partial class CONTRATOS_LISTA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _nombre;
		
		private string _descripcion;
		
		private System.DateTime _fechaCreacion;
		
		private int _codigoContrato;
		
		private System.Guid _token;
		
		private string _empresaNombre;
		
		private int _empresaRut;
		
		private char _empresaDv;
		
		private System.Guid _empresaToken;
		
		private string _nivelNombre;
		
		private System.Guid _nivelToken;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OnfechaCreacionChanging(System.DateTime value);
    partial void OnfechaCreacionChanged();
    partial void OncodigoContratoChanging(int value);
    partial void OncodigoContratoChanged();
    partial void OntokenChanging(System.Guid value);
    partial void OntokenChanged();
    partial void OnempresaNombreChanging(string value);
    partial void OnempresaNombreChanged();
    partial void OnempresaRutChanging(int value);
    partial void OnempresaRutChanged();
    partial void OnempresaDvChanging(char value);
    partial void OnempresaDvChanged();
    partial void OnempresaTokenChanging(System.Guid value);
    partial void OnempresaTokenChanged();
    partial void OnnivelNombreChanging(string value);
    partial void OnnivelNombreChanged();
    partial void OnnivelTokenChanging(System.Guid value);
    partial void OnnivelTokenChanged();
    #endregion
		
		public CONTRATOS_LISTA()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="CONT_NOMBRE", Storage="_nombre", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="CONT_DESCRIPCION", Storage="_descripcion", DbType="VarChar(1000)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="CONT_FECHACREACION", Storage="_fechaCreacion", DbType="DateTime NOT NULL")]
		public System.DateTime fechaCreacion
		{
			get
			{
				return this._fechaCreacion;
			}
			set
			{
				if ((this._fechaCreacion != value))
				{
					this.OnfechaCreacionChanging(value);
					this.SendPropertyChanging();
					this._fechaCreacion = value;
					this.SendPropertyChanged("fechaCreacion");
					this.OnfechaCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="CONT_CODIGOCONTRATO", Storage="_codigoContrato", DbType="Int NOT NULL")]
		public int codigoContrato
		{
			get
			{
				return this._codigoContrato;
			}
			set
			{
				if ((this._codigoContrato != value))
				{
					this.OncodigoContratoChanging(value);
					this.SendPropertyChanging();
					this._codigoContrato = value;
					this.SendPropertyChanged("codigoContrato");
					this.OncodigoContratoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="CONT_TOKEN", Storage="_token", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid token
		{
			get
			{
				return this._token;
			}
			set
			{
				if ((this._token != value))
				{
					this.OntokenChanging(value);
					this.SendPropertyChanging();
					this._token = value;
					this.SendPropertyChanged("token");
					this.OntokenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="EMPR_NOMBRE", Storage="_empresaNombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string empresaNombre
		{
			get
			{
				return this._empresaNombre;
			}
			set
			{
				if ((this._empresaNombre != value))
				{
					this.OnempresaNombreChanging(value);
					this.SendPropertyChanging();
					this._empresaNombre = value;
					this.SendPropertyChanged("empresaNombre");
					this.OnempresaNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="EMPR_RUT", Storage="_empresaRut", DbType="Int NOT NULL")]
		public int empresaRut
		{
			get
			{
				return this._empresaRut;
			}
			set
			{
				if ((this._empresaRut != value))
				{
					this.OnempresaRutChanging(value);
					this.SendPropertyChanging();
					this._empresaRut = value;
					this.SendPropertyChanged("empresaRut");
					this.OnempresaRutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="EMPR_DV", Storage="_empresaDv", DbType="Char(1) NOT NULL")]
		public char empresaDv
		{
			get
			{
				return this._empresaDv;
			}
			set
			{
				if ((this._empresaDv != value))
				{
					this.OnempresaDvChanging(value);
					this.SendPropertyChanging();
					this._empresaDv = value;
					this.SendPropertyChanged("empresaDv");
					this.OnempresaDvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="EMPR_TOKEN", Storage="_empresaToken", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid empresaToken
		{
			get
			{
				return this._empresaToken;
			}
			set
			{
				if ((this._empresaToken != value))
				{
					this.OnempresaTokenChanging(value);
					this.SendPropertyChanging();
					this._empresaToken = value;
					this.SendPropertyChanged("empresaToken");
					this.OnempresaTokenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="NVL_NOMBRE", Storage="_nivelNombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nivelNombre
		{
			get
			{
				return this._nivelNombre;
			}
			set
			{
				if ((this._nivelNombre != value))
				{
					this.OnnivelNombreChanging(value);
					this.SendPropertyChanging();
					this._nivelNombre = value;
					this.SendPropertyChanged("nivelNombre");
					this.OnnivelNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="NVL_TOKEN", Storage="_nivelToken", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid nivelToken
		{
			get
			{
				return this._nivelToken;
			}
			set
			{
				if ((this._nivelToken != value))
				{
					this.OnnivelTokenChanging(value);
					this.SendPropertyChanging();
					this._nivelToken = value;
					this.SendPropertyChanged("nivelToken");
					this.OnnivelTokenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class CONTRATOS
	{
		
		private string _nombre;
		
		private string _descripcion;
		
		private string _codigo;
		
		private string _tokenEmpresa;
		
		private string _tokenNivelOrranizacional;
		
		private string _token;
		
		public CONTRATOS()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this._descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo", CanBeNull=false)]
		public string codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this._codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tokenEmpresa", CanBeNull=false)]
		public string tokenEmpresa
		{
			get
			{
				return this._tokenEmpresa;
			}
			set
			{
				if ((this._tokenEmpresa != value))
				{
					this._tokenEmpresa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tokenNivelOrranizacional", CanBeNull=false)]
		public string tokenNivelOrranizacional
		{
			get
			{
				return this._tokenNivelOrranizacional;
			}
			set
			{
				if ((this._tokenNivelOrranizacional != value))
				{
					this._tokenNivelOrranizacional = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_token")]
		public string token
		{
			get
			{
				return this._token;
			}
			set
			{
				if ((this._token != value))
				{
					this._token = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class CONTRATOS_NIVEL_LISTA
	{
		
		private System.Guid _tokenContrato;
		
		private string _nombreContrato;
		
		private string _codigoContrato;
		
		public CONTRATOS_NIVEL_LISTA()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="CONT_TOKEN", Storage="_tokenContrato")]
		public System.Guid tokenContrato
		{
			get
			{
				return this._tokenContrato;
			}
			set
			{
				if ((this._tokenContrato != value))
				{
					this._tokenContrato = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="CONT_NOMBRE", Storage="_nombreContrato", CanBeNull=false)]
		public string nombreContrato
		{
			get
			{
				return this._nombreContrato;
			}
			set
			{
				if ((this._nombreContrato != value))
				{
					this._nombreContrato = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="CONT_CODIGOCONTRATO", Storage="_codigoContrato", CanBeNull=false)]
		public string codigoContrato
		{
			get
			{
				return this._codigoContrato;
			}
			set
			{
				if ((this._codigoContrato != value))
				{
					this._codigoContrato = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class CONTRATOS_NIVEL
	{
		
		private System.Guid _tokenNivel;
		
		private System.Guid _tokenEmpresa;
		
		public CONTRATOS_NIVEL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tokenNivel")]
		public System.Guid tokenNivel
		{
			get
			{
				return this._tokenNivel;
			}
			set
			{
				if ((this._tokenNivel != value))
				{
					this._tokenNivel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tokenEmpresa")]
		public System.Guid tokenEmpresa
		{
			get
			{
				return this._tokenEmpresa;
			}
			set
			{
				if ((this._tokenEmpresa != value))
				{
					this._tokenEmpresa = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
