#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Endpoints.HistoryCase.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	public partial class historycaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public historycaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public historycaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public historycaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public historycaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CREATEHISTORYCASE> CREATEHISTORYCASE
		{
			get
			{
				return this.GetTable<CREATEHISTORYCASE>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class CREATEHISTORYCASE
	{
		
		private string _IDENTIFIER;
		
		private string _DESCRIPTION;
		
		private System.Guid _CASETOKEN;
		
		private System.Guid _HISTORYTOKEN;
		
		public CREATEHISTORYCASE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="IDENTIFICADOR", Storage="_IDENTIFIER", CanBeNull=false)]
		public string IDENTIFIER
		{
			get
			{
				return this._IDENTIFIER;
			}
			set
			{
				if ((this._IDENTIFIER != value))
				{
					this._IDENTIFIER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="DESCRIPCION", Storage="_DESCRIPTION", CanBeNull=false)]
		public string DESCRIPTION
		{
			get
			{
				return this._DESCRIPTION;
			}
			set
			{
				if ((this._DESCRIPTION != value))
				{
					this._DESCRIPTION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="TOKEN", Storage="_CASETOKEN")]
		public System.Guid CASETOKEN
		{
			get
			{
				return this._CASETOKEN;
			}
			set
			{
				if ((this._CASETOKEN != value))
				{
					this._CASETOKEN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="HISTORIATOKEN", Storage="_HISTORYTOKEN")]
		public System.Guid HISTORYTOKEN
		{
			get
			{
				return this._HISTORYTOKEN;
			}
			set
			{
				if ((this._HISTORYTOKEN != value))
				{
					this._HISTORYTOKEN = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
